"""initial_schema

Revision ID: fede628e0a19
Revises:
Create Date: 2026-06-09 09:57:37.871513

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'fede628e0a19'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
